### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by NimaSoroush** [xfumihiro/jest-puppeteer-example#1]
Hi @xfumihiro,

This is really cool that you have put this example together and would be definitely very helpful.
While ago I started a project with the same purpose and has a full integration of jest and puppeteer in it.
https://github.com/NimaSoroush/differencify
jest section:
https://github.com/NimaSoroush/differencify#usage-with-jest

Maybe worth linking these two projects together. Let me know what are your thoughts?

**Comment by xfumihiro** [comment]
Hey @NimaSoroush that seems great!
Love to contribute my knowledge on this to **differencify**.

**Comment by NimaSoroush** [comment]
Awesome!
I like the idea of extending `jest-environment-node`. This will get rid of side effect methods like `setup` and `tearDown`

I will put an issue on Differencify project regarding this. 

Lets discuss details in [Gitter](https://gitter.im) and also see what else we can integrate
