### ISSUE TITLE
What is the reason for all the wsEndpoint stuff?

### ISSUE THREAD

**Issue by alanshaw** [xfumihiro/jest-puppeteer-example#10]
I can't see an explanation [here](https://facebook.github.io/jest/docs/en/22.0/puppeteer.html) or in this repo...

Why is it so complicated?

**Comment by donysukardi** [comment]
This ensures that only one instance of Chromium is running for all the test suites. The alternative is to launch a new Chromium instance for each test suite, which is slower and more expensive.

**Comment by donysukardi** [comment]
`setup.js` runs once globally to launch the Chromium and `puppeteer_environment.js` hooks each test suite up to that instance by using `.connnet`

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerconnectoptions

**Comment by alanshaw** [comment]
I see, thank you!
