### ISSUE TITLE
How to test local server not online?

### ISSUE THREAD

**Issue by ycjcl868** [xfumihiro/jest-puppeteer-example#14]
The examples show test `google.com`, it's online server.

**Comment by binhxn** [comment]
@ycjcl868 Have you tried changing the URL to your local server? i.e.
`await page.goto('localhost:3000')`

**Comment by campa** [comment]
I'm trying too, but I have not a server.js file in my project ? How I ca create it ?

`> JEST_PUPPETEER_CONFIG=e2e/jest-puppeteer.config.js jest --config=e2e/jest.e2e.config.js
Determining test suites to run...internal/modules/cjs/loader.js:583
    throw err;
   ^
Error: Cannot find module '/media/[my-path]/server.js'
`
Any suggestion ?
