### ISSUE TITLE
Setup running multiple times

### ISSUE THREAD

**Issue by VictorChen** [xfumihiro/jest-puppeteer-example#2]
Is it expected that the setup runs once PER test? This is the output I get:

```
Determining test suites to run...Setup Puppeteer Environment.
Setup Puppeteer Test Environment.
 PASS  __tests__/test3.js
Setup Puppeteer Test Environment.
 PASS  __tests__/test1.js
Setup Puppeteer Test Environment.
 PASS  __tests__/test2.js
Setup Puppeteer Test Environment.
 PASS  __tests__/test5.js
Setup Puppeteer Test Environment.
 PASS  __tests__/test4.js

Test Suites: 5 passed, 5 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        2.049s
Ran all test suites.
Teardown Puppeteer Environment.
```

**Comment by xfumihiro** [comment]
Nope. It should only setup/teardown once.

**Comment by xfumihiro** [comment]
Okay, there's something wrong with the Jest test result console output.

I tried add a timestamp to console output
```js
module.exports = async function() {
  console.log(chalk.green('Setup Puppeteer Environment. '))
  console.log(chalk.yellow('timestamp' + Date.now()))
  const browser = await puppeteer.launch({ headless: false })
  global.__BROWSER__ = browser
  mkdirp.sync(DIR)
  fs.writeFileSync(path.join(DIR, 'wsEndpoint'), browser.wsEndpoint())
}
```

Here's the result of it.
![screen shot 2018-01-06 at 3 34 21 am](https://user-images.githubusercontent.com/12194969/34625128-8dc41890-f292-11e7-938f-6bf7b02bc649.png)

So the setup/teardown script still have only been called once.

**Comment by xfumihiro** [comment]
"Test Environments" are being setup/teardown on every test suite.
So this is normal.

Made a slight change on master to be clear on this:
![screen shot 2018-01-06 at 3 53 08 am](https://user-images.githubusercontent.com/12194969/34625825-28db7f4c-f295-11e7-9c82-2af7aa47c989.png)

**Comment by VictorChen** [comment]
ah thought it was the same setup as Puppeteer, thanks!
