### ISSUE TITLE
sample tests are now broken

### ISSUE THREAD

**Issue by Pyrolistical** [xfumihiro/jest-puppeteer-example#8]
chrome changed behaviour where if you are on google.com, it goes to startup page instead of the actual site. your sample tests are hitting this case and never finishing since you are never on an actual website

**Comment by xfumihiro** [comment]
Thanks for raising the issue.
Where should we go now? Bing.com? 😂

**Comment by xfumihiro** [comment]
It works fine on my laptop.
Close it for now.
