### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by RumenTech** [xfumihiro/jest-puppeteer-example#9]
@xfumihiro 

First of all, thanks for sharing the setup configuration, it really helped me to get started with jest + puppeteer.

With my current configuration, I cannot get the reference of global document variable.
I understand that it replaces `jest-environment-jsdom` with `jest-environment-node`.
Can you please let me know what I'm missing here & how your example code works?

Thank you.

```
it('should load without error', async () => {
    let text = await page.evaluate(() => document.body.textContent)
    expect(text).toContain('google')
})
```

I'm not blocked though, I'm using `page.$eval` to get element handle.

**Comment by xfumihiro** [comment]
@RumenTech can you share your configs?

**Comment by RumenTech** [comment]
Sorry, I think I have figured that out, all good now :)
I was using `node` for unit tests and one of unit tests complained `document` reference.

I'll appreciate if you help me with these questions when you get a chance.

#### 1. document reference
The following code is working fine, however I'm still not sure how `document` comes available in this line.
let text = await page.evaluate(() => document.body.textContent)

#### 2. use node env for enzyme unit tests
My config below  `jsdom` for enzyme unit tests, `node` for puppeteer tests.
Is there any way to set up one config using node env?
In that case, how to make `document` available in unit tests?

#### 3. logging important console messages
How to log console messages which are printed from actual code?
I'm doing the following for each test suite's `beforeAll`.
Is there any way to register this listener only once somewhere?
```
    page = await global.__BROWSER__.newPage()
    // await page.setViewport(viewports['XL'])
    page.on('console', message => {
      const text = message.text()
      if (message.type === 'error' || text.includes('@puppeteer')) {
        console.log(text)
      }
    })
```

Thank you in advance.


My Jest configuration
```
// jest.config.js

let configuration = {
  // unit tests - jest with enzyme
  unit: {
    moduleNameMapper: {
      "\\.(css|jpg|png|svg)$": "<rootDir>/app/react_spa/__tests__/config/empty_module.js", 
      "root\/(.*)$": "<rootDir>/app/react_spa/javascript/$1",
      "public_assets\/(.*)$": "<rootDir>/app/assets/$1"
    },
    testMatch       : ['**/__tests__/**/?(*.)(spec|test).js'],
    setupFiles      : ['./app/react_spa/__tests__/config/sync_enzyme_setup.js'],
    testEnvironment : 'jsdom',
  },

  // e2e tests - jest with puppeteer
  e2e: {
    verbose         : true,
    testMatch       : ['**/__tests__/**/?(*.)(spec|test).js'],
    setupFiles      : ['./app/react_spa/__tests__/config/global_vars_setup.js'],
    globalSetup     : './app/react_spa/__tests__/config/async_global_setup.js',
    globalTeardown  : './app/react_spa/__tests__/config/async_global_teardown.js',
    testEnvironment : './app/react_spa/__tests__/config/puppeteer_environment.js',
  }
};

let testModesMap = {
  'unit'      : 'unit',
  'e2e'       : 'e2e',
  'e2e_debug' : 'e2e',
}

const mode = testModesMap[ process.env.TEST_MODE || 'unit' ]

module.exports = configuration[ mode ];
```

**Comment by xfumihiro** [comment]
@RumenTech glad things work out for you :)
for 1 & 2, you might want to check out puppeteer code to see how it works.
as for 3, FWIK jest might swallow any test environment's console messages (as it is trying to produce the testing results), you might need to check out jest code as well.
